name: Deploy Nginx

on:
  push:
    branches:
    - 'main'
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      run: |
        sudo apt update
        sudo snap install google-cloud-sdk --classic
    - name: iCheck gcloud cli Version
      run: |
        gcloud --version

    # - name: install the gcloud cli
    #   uses: google-github-actions/setup-gcloud@v0
    #   with:
    #     project_id: ${{ secrets.GOOGLE_PROJECT }}
    #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    #     export_default_credentials: true

    - name: build and push the docker image to artifact registry
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        gcloud auth configure-docker us-east1-docker.pkg.dev
        gcloud auth activate-service-account --key-file=$SERVICE_ACCOUNT_KEY 
        docker build -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT/my-repo/my-repo:latest .
        docker push us-east1-docker.pkg.dev/$GOOGLE_PROJECT/my-repo/my-repo:latest
