name: Deploy Nginx

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        run: |
          sudo apt update
          sudo snap install google-cloud-sdk --classic
          gcloud --version

      - name: Check docker Version
        run: |
          docker --version || true

      - name: Set up service account key
        run: |
          # mkdir -p $HOME/gcloud
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" | jq . > key.json
          # chmod 664 $HOME/gcloud/key.json










# name: Deploy Nginx

# on:
#   push:
#     branches:
#     - 'main'
#   workflow_dispatch: 

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:

#     - name: code checkout
#       uses: actions/checkout@v2

#     - name: install the gcloud cli
#       run: |
#         sudo apt update
#         sudo snap install google-cloud-sdk --classic
#     - name: Check gcloud cli Version
#       run: |
#         gcloud --version

#     - name: Check docker Version
#       run: |
#         docker --version || true

#     - name: Set up service account key
#       run: |
#         mkdir -p $HOME/gcloud
#         echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" | jq . > $HOME/gcloud/key.json
#         chmod 664 $HOME/gcloud/key.json

#     - name: Set up service account key
#       run: |
#         cd $HOME/gcloud/
#         pwd
#         ls
#         ls -l
#     - name: build and push the docker image to artifact registry
#       run: |
#           cd $HOME/gcloud/
#           cat key.json
#           gcloud auth activate-service-account --key-file=key.json
#           gcloud auth configure-docker us-east1-docker.pkg.dev --quiet


#     - name: install the gcloud cli
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         project_id: ${{ secrets.GOOGLE_PROJECT }}
#         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#         export_default_credentials: true

#     - name: build and push the docker image to artifact registry
#       env:
#         GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#       run: |
#         gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
#         docker build -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT/my-repo/my-repo:latest .
#         docker push us-east1-docker.pkg.dev/$GOOGLE_PROJECT/my-repo/my-repo:latest
